name: test hello
on: push

jobs:
  my-job:
    name: hello job
    runs-on: ubuntu-latest
    steps:
    - name: print hello steps
      env:
        MY_VAR: Hello, My Name Is
        FIRST_NAME: Zeng
        MIDDLE_NAME: Hai
        LAST_NAME: Ming
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.