name: test hello
on: 
    workflow_dispatch:
    push:

jobs:
  my-job:
    name: hello job
    runs-on: ubuntu-latest
    steps:
    - name: print hello steps
      env:
        MY_VAR: Hello, 爱海游。 My Name Is
        FIRST_NAME: Zeng
        MIDDLE_NAME: Hai
        LAST_NAME: Ming
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.

  zf-job:
    runs-on: ubuntu-latest
    steps:
     - name: print ihaiu steps
       env:
           MY_NAME: http://blog.ihaiu.com
       run: |
          echo $MY_NAME
      
